project_id = "bnupitnrxyferelwroas"
[functions.mercadopago-create-preference]
verify_jwt = false

[functions.mercadopago-config]
verify_jwt = false

[functions.mercadopago-process-payment]
verify_jwt = false

[functions.mercadopago-check-status]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.admin-create-lifetime]
verify_jwt = false
